// Local-only spell library backed by localStorage. The bridge generates the
// schema; this module owns persistence and the SSE round-trip.
import { validateSpell } from './spellSchema.js'

const KEY = 'woid.spells'

function read() {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw)
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

function write(spells) {
  localStorage.setItem(KEY, JSON.stringify(spells))
}

export function listSpells() {
  return read().sort((a, b) => b.createdAt - a.createdAt)
}

export function getSpell(id) {
  return read().find((s) => s.id === id) ?? null
}

export function deleteSpell(id) {
  write(read().filter((s) => s.id !== id))
}

function newId() {
  return `spell_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`
}

// Calls /api/spells/generate (Vite dev plugin), parses the SSE stream, and
// persists the result on success.
//   onStage(stage, message) — progress label
//   onPartial(text)         — accumulated streaming text from the model
// The spell's name comes from the schema Claude returns.
export async function generateSpell({ prompt, onStage, onPartial }) {
  const res = await fetch('/api/spells/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ prompt }),
  })
  if (!res.ok || !res.body) throw new Error(`HTTP ${res.status}`)

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buf = ''
  let schema = null
  let errorMessage = null

  while (true) {
    const { value, done } = await reader.read()
    if (done) break
    buf += decoder.decode(value, { stream: true })
    const events = buf.split(/\n\n/)
    buf = events.pop() ?? ''
    for (const evChunk of events) {
      const lines = evChunk.split('\n')
      let eventType = 'message'
      const dataLines = []
      for (const line of lines) {
        if (line.startsWith('event:')) eventType = line.slice(6).trim()
        else if (line.startsWith('data:')) dataLines.push(line.slice(5).trimStart())
      }
      const data = dataLines.join('\n')
      if (!data) continue
      let parsed
      try { parsed = JSON.parse(data) } catch { continue }

      if (eventType === 'stage') {
        onStage?.(parsed.stage, parsed.message || '')
      } else if (eventType === 'partial') {
        onPartial?.(parsed.text || '')
      } else if (eventType === 'done') {
        schema = parsed.schema
      } else if (eventType === 'error') {
        errorMessage = parsed.message || 'stream error'
      }
    }
  }

  if (errorMessage) throw new Error(errorMessage)
  if (!schema) throw new Error('no schema returned')

  const errors = validateSpell(schema)
  if (errors.length) throw new Error(`schema validation failed: ${errors.join('; ')}`)

  const spell = {
    id: newId(),
    name: schema.name || 'Untitled spell',
    prompt,
    schema,
    createdAt: Date.now(),
  }
  write([spell, ...read()])
  return spell
}

// Walks accumulated text looking for fully-balanced top-level objects inside
// the first JSON array. Returns whatever it has parsed so far.
function partialItems(text) {
  if (!text) return []
  const start = text.indexOf('[')
  if (start < 0) return []
  let i = start + 1
  let depth = 0
  let inStr = false
  let escape = false
  let itemStart = -1
  const items = []
  while (i < text.length) {
    const c = text[i]
    if (escape) { escape = false; i++; continue }
    if (c === '\\') { escape = true; i++; continue }
    if (c === '"') { inStr = !inStr; i++; continue }
    if (!inStr) {
      if (c === '{') { if (depth === 0) itemStart = i; depth++ }
      else if (c === '}') {
        depth--
        if (depth === 0 && itemStart >= 0) {
          try { items.push(JSON.parse(text.slice(itemStart, i + 1))) } catch {}
          itemStart = -1
        }
      } else if (c === ']' && depth === 0) break
    }
    i++
  }
  return items
}

// Returns 3 spell idea options ({ name, prompt }) generated by local Claude.
// Streams partial text via onPartial(text) and stage labels via onStage.
// onItem(item, index) fires each time a complete suggestion is parsed.
export async function suggestSpells({ onStage, onPartial, onItem } = {}) {
  const res = await fetch('/api/spells/suggest', { method: 'POST' })
  if (!res.ok || !res.body) throw new Error(`HTTP ${res.status}`)

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buf = ''
  let suggestions = null
  let errorMessage = null
  let lastEmittedIndex = -1

  while (true) {
    const { value, done } = await reader.read()
    if (done) break
    buf += decoder.decode(value, { stream: true })
    const events = buf.split(/\n\n/)
    buf = events.pop() ?? ''
    for (const evChunk of events) {
      const lines = evChunk.split('\n')
      let eventType = 'message'
      const dataLines = []
      for (const line of lines) {
        if (line.startsWith('event:')) eventType = line.slice(6).trim()
        else if (line.startsWith('data:')) dataLines.push(line.slice(5).trimStart())
      }
      const data = dataLines.join('\n')
      if (!data) continue
      let parsed
      try { parsed = JSON.parse(data) } catch { continue }

      if (eventType === 'stage') {
        onStage?.(parsed.stage, parsed.message || '')
      } else if (eventType === 'partial') {
        const text = parsed.text || ''
        onPartial?.(text)
        const items = partialItems(text)
        for (let idx = lastEmittedIndex + 1; idx < items.length; idx++) {
          if (items[idx] && typeof items[idx].name === 'string' && typeof items[idx].prompt === 'string') {
            onItem?.(items[idx], idx)
            lastEmittedIndex = idx
          }
        }
      } else if (eventType === 'done') {
        suggestions = parsed.suggestions
      } else if (eventType === 'error') {
        errorMessage = parsed.message || 'stream error'
      }
    }
  }

  if (errorMessage) throw new Error(errorMessage)
  if (!Array.isArray(suggestions)) throw new Error('no suggestions returned')
  return suggestions
}
