#!/usr/bin/env bash
# Swap the llama.cpp server to a different catalog entry.
#
# Usage:
#   ./scripts/swap-local-model.sh gemma-4-E4B-it-Q4_K_M
#   ./scripts/swap-local-model.sh gemma-4-31B-it-Q4_K_M --extra='--ctx-size 16384'

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$HERE/catalog.json"
ENVFILE="$HERE/.env.llama-cpp"
COMPOSE="$HERE/docker-compose.yml"

if [ $# -lt 1 ]; then
  echo "usage: $0 <catalog-id> [--extra='<llama-server flags>']" >&2
  echo "" >&2
  echo "Available ids:" >&2
  jq -r '.[] | "  \(.id)  (\(.tier)) — \(.notes)"' "$CATALOG" >&2
  exit 1
fi

ID="$1"; shift || true
EXTRA=""
for arg in "$@"; do
  case "$arg" in
    --extra=*) EXTRA="${arg#--extra=}" ;;
  esac
done

ENTRY=$(jq -r --arg id "$ID" '.[] | select(.id == $id)' "$CATALOG")
if [ -z "$ENTRY" ]; then
  echo "error: no entry '$ID' in $CATALOG" >&2
  exit 1
fi

HF_REPO=$(jq -r '.hf_repo' <<<"$ENTRY")
QUANT=$(jq -r '.quant' <<<"$ENTRY")

# Cap context for larger models so KV cache fits alongside weights.
DEFAULT_CTX=16384

cat > "$ENVFILE" <<EOF
# Generated by scripts/swap-local-model.sh
LLAMA_CPP_HF_REPO=$HF_REPO
LLAMA_CPP_QUANT=$QUANT
LLAMA_CPP_EXTRA_ARGS=--ctx-size $DEFAULT_CTX $EXTRA
EOF

echo "[swap] id=$ID repo=$HF_REPO quant=$QUANT ctx=$DEFAULT_CTX extra='$EXTRA'"
echo "[swap] restarting llama-cpp service..."
docker compose --env-file "$ENVFILE" -f "$COMPOSE" up -d --force-recreate llama-cpp
echo ""
echo "[swap] server at http://localhost:18080/v1"
echo "[swap] wait for /health, then in agent-sandbox/.env set:"
echo "  LOCAL_LLM_BASE_URL=http://host.docker.internal:18080/v1"
echo "[swap] restart pi-bridge so it picks up the new env"
